#!/usr/bin/env node --harmony

// requires
var execSync = require('child_process').execSync;
var exec = require('child_process').exec;
var path = require('path');
var fs = require('fs');

var gitRoot = execSync('git rev-parse --show-toplevel');

console.log('running pre-commit checks...');

try {
  execSync("gulp lint", { cwd: gitRoot });
  console.log("OK");
} catch(e) {
  console.log(e.stdout.toString());
  process.exit(1);
}
